---
framework: mocha
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "./test/index.test.js"
postMerge:
  pattern:
    - "./test/index.test.js"
postRun:
     command:
        - yarn --version
version: 1.0
